# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AhmadTestGithubConnection'
    subscriptionId: '80ebef40-3f7f-4972-b829-72efcd567faf'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'New-RGroup'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'maintemplate.json'
    overrideParameters: '-projectName Test1Project -linkedTemplateUri https://raw.githubusercontent.com/Ahmad12506/CustomerSideRepo/main/parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTempl'
